application: mecproyecto
version: 1
runtime: python
api_version: 1

handlers:
    
- {static_dir: static,          url: /static}
- {static_dir: static/image,    url: /image}
- {static_dir: static/css,      url: /css}
- {static_dir: static/scripts,  url: /scripts}
- {static_dir: static/swf,      url: /swf}
- {static_dir: static/js,       url: /js}
    
- url: .*
  script: main.py
